[versions]
# Application properties
minSdk = "23"
targetSdk = "36"

# Libraries
agp = "8.13.1"
kotlin = "2.2.21"
ksp = "2.2.21-2.0.4"
androidx-activity = "1.12.0"
androidx-core = "1.17.0"
androidx-core-splashscreen = "1.2.0"
androidx-material3 = "1.4.0"
compose-hot-reload = "1.0.0"
compose-kmp = "1.9.3"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.9.0"
material-kmp = "1.9.0"
material-android = "1.13.0"
robolectric = "4.16"
room = "2.8.4"
sqlite = "2.6.2"
desugar = "2.1.5"
koin = "4.1.1"
kermit = "2.0.8"
datastore = "1.2.0"
ktor = "3.3.3"


[libraries]
# Androidx
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-core-splashscreen" }

# Material
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material-kmp" }
material3-desktop = { module = "org.jetbrains.compose.material3:material3-desktop", version.ref = "material-kmp" }
material3-android = { module = "androidx.compose.material3:material3", version.ref = "androidx-material3" }
material-android = { module = "com.google.android.material:material", version.ref = "material-android" }

# Kotlinx
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# Testing
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

# Dependency injection
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose-viewmodel-navigation", version.ref = "koin" }

# Database
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

# Logging
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
kermit-io = { module = "co.touchlab:kermit-io", version.ref = "kermit" }
kermit-koin = { module = "co.touchlab:kermit-koin", version.ref = "kermit" }

# Datastore (Store settings/configurations)
datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

# Ktor
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-content-encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-serialization-protobuf = { module = "io.ktor:ktor-serialization-kotlinx-protobuf", version.ref = "ktor" }

# Others
android-desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }


[plugins]
# Multiplatform
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-kmp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
room-kmp = { id = "androidx.room", version.ref = "room" }

# Android
application = { id = "com.android.application", version.ref = "agp" }
library = { id = "com.android.library", version.ref = "agp" }

# Other
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-hot-reload = { id = "org.jetbrains.compose.hot-reload", version.ref = "compose-hot-reload" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }


[bundles]
ktor = ["ktor-core", "ktor-content-negotiation", "ktor-content-encoding", "ktor-logging", "ktor-serialization-json", "ktor-serialization-protobuf"]